from enum import StrEnum


class VersionStatus(StrEnum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    ARCHIVED = "ARCHIVED"


class ModuleType(StrEnum):
    READING = "READING"
    LISTENING = "LISTENING"
    WRITING = "WRITING"


class TimerMode(StrEnum):
    COUNTDOWN = "COUNTDOWN"
    COUNT_UP = "COUNT_UP"


class AttemptStatus(StrEnum):
    IN_PROGRESS = "IN_PROGRESS"
    SUBMITTED = "SUBMITTED"
    AUTO_SUBMITTED = "AUTO_SUBMITTED"
    INTERRUPTED = "INTERRUPTED"
    ABANDONED = "ABANDONED"


class FinishedReason(StrEnum):
    USER_SUBMIT = "USER_SUBMIT"
    TIME_EXPIRED = "TIME_EXPIRED"
    AFK_TIMEOUT = "AFK_TIMEOUT"
    USER_EXIT = "USER_EXIT"


class AssetType(StrEnum):
    LISTENING_AUDIO = "LISTENING_AUDIO"
    WRITING_TASK_IMAGE = "WRITING_TASK_IMAGE"
    QUESTION_IMAGE = "QUESTION_IMAGE"


class EventType(StrEnum):
    ANSWER_CHANGED = "ANSWER_CHANGED"
    QUESTION_VISITED = "QUESTION_VISITED"
    PASSAGE_CHANGED = "PASSAGE_CHANGED"
    HIGHLIGHT_CREATED = "HIGHLIGHT_CREATED"
    HIGHLIGHT_REMOVED = "HIGHLIGHT_REMOVED"
    FLAG_CHANGED = "FLAG_CHANGED"
    WRITING_UPDATED = "WRITING_UPDATED"
    AFK_DETECTED = "AFK_DETECTED"
    SUBMITTED = "SUBMITTED"
