import type { ComponentType } from "react";
import { z } from "zod";
import { MatchingEditor, MatchingHeadingsEditor, MultipleChoiceEditor, MultipleChoiceMultipleEditor, StructuredCompletionEditor, TextCompletionEditor, TrueFalseNotGivenEditor, VisualLabellingEditor, type EditorProps } from "./editors";
import { MatchingHeadingsRenderer, MatchingRenderer, MultipleChoiceMultipleRenderer, MultipleChoiceRenderer, StructuredCompletionRenderer, TextCompletionRenderer, TrueFalseNotGivenRenderer, VisualLabellingRenderer, type RendererProps } from "./renderers";
import type { QuestionGroupModel, QuestionType } from "./types";

export type QuestionTypeDefinition = { id: QuestionType; label: string; category: "reading" | "listening" | "shared"; BuilderEditor: ComponentType<EditorProps>; AnswerKeyEditor: ComponentType<EditorProps>; ExamRenderer: ComponentType<RendererProps>; ReviewRenderer: ComponentType<RendererProps>; responseSchema: z.ZodType; configSchema: z.ZodType; createDefault: (number: number) => QuestionGroupModel };
const optionSchema = z.object({ id: z.string().uuid(), label: z.string().min(1), text: z.string().min(1) });
const textQuestion = (number: number) => ({ id: crypto.randomUUID(), number, prompt: "Enter the answer.", config: { max_words: 2, max_numbers: 1 }, answer_key: { kind: "TEXT", accepted: ["sample answer"], case_sensitive: false }, order_index: 0 });
const newOptions = () => [{ id: crypto.randomUUID(), label: "A", text: "Option A" }, { id: crypto.randomUUID(), label: "B", text: "Option B" }, { id: crypto.randomUUID(), label: "C", text: "Option C" }];

const definitions: QuestionTypeDefinition[] = [
  { id: "multiple_choice", label: "Multiple Choice — Single", category: "shared", BuilderEditor: MultipleChoiceEditor, AnswerKeyEditor: MultipleChoiceEditor, ExamRenderer: MultipleChoiceRenderer, ReviewRenderer: MultipleChoiceRenderer, responseSchema: z.string(), configSchema: z.object({ options: z.array(optionSchema).min(2) }), createDefault: (number) => { const options = newOptions().slice(0, 2); return { question_type: "multiple_choice", instruction: "Choose the correct answer.", config: {}, order_index: 0, questions: [{ id: crypto.randomUUID(), number, prompt: "Question prompt", config: { options }, answer_key: { kind: "SINGLE_OPTION", value: options[0].id }, order_index: 0 }] }; } },
  { id: "multiple_choice_multiple", label: "Multiple Choice — Multiple", category: "shared", BuilderEditor: MultipleChoiceMultipleEditor, AnswerKeyEditor: MultipleChoiceMultipleEditor, ExamRenderer: MultipleChoiceMultipleRenderer, ReviewRenderer: MultipleChoiceMultipleRenderer, responseSchema: z.array(z.string()), configSchema: z.object({}), createDefault: (number) => { const options = newOptions(); return { question_type: "multiple_choice_multiple", instruction: "Choose the correct answers.", config: {}, order_index: 0, questions: [{ id: crypto.randomUUID(), number, prompt: "Question prompt", config: { options, min_selections: 2, max_selections: 2 }, answer_key: { kind: "MULTIPLE_OPTIONS", values: options.slice(0, 2).map((item) => item.id), order_matters: false }, order_index: 0 }] }; } },
  { id: "true_false_not_given", label: "True / False / Not Given", category: "reading", BuilderEditor: TrueFalseNotGivenEditor, AnswerKeyEditor: TrueFalseNotGivenEditor, ExamRenderer: TrueFalseNotGivenRenderer, ReviewRenderer: TrueFalseNotGivenRenderer, responseSchema: z.string(), configSchema: z.object({}), createDefault: (number) => ({ question_type: "true_false_not_given", instruction: "Do the statements agree with the passage?", config: {}, order_index: 0, questions: [{ id: crypto.randomUUID(), number, prompt: "Statement", config: {}, answer_key: { kind: "SINGLE_OPTION", value: "TRUE" }, order_index: 0 }] }) },
  { id: "text_completion", label: "Text Completion", category: "shared", BuilderEditor: TextCompletionEditor, AnswerKeyEditor: TextCompletionEditor, ExamRenderer: TextCompletionRenderer, ReviewRenderer: TextCompletionRenderer, responseSchema: z.string(), configSchema: z.object({}), createDefault: (number) => ({ question_type: "text_completion", instruction: "Complete the text using the stated limit.", config: {}, order_index: 0, questions: [textQuestion(number)] }) },
  { id: "matching_headings", label: "Matching Headings", category: "reading", BuilderEditor: MatchingHeadingsEditor, AnswerKeyEditor: MatchingHeadingsEditor, ExamRenderer: MatchingHeadingsRenderer, ReviewRenderer: MatchingHeadingsRenderer, responseSchema: z.string(), configSchema: z.object({}), createDefault: (number) => { const options = [{ id: crypto.randomUUID(), label: "i", text: "First heading" }, { id: crypto.randomUUID(), label: "ii", text: "Second heading" }]; return { question_type: "matching_headings", instruction: "Choose the correct heading for each paragraph.", config: { options, allow_option_reuse: false }, order_index: 0, questions: [{ id: crypto.randomUUID(), number, prompt: "Choose a heading.", config: { target_block_id: "" }, answer_key: { kind: "SINGLE_OPTION", value: options[0].id }, order_index: 0 }] }; } },
  { id: "matching", label: "Matching", category: "shared", BuilderEditor: MatchingEditor, AnswerKeyEditor: MatchingEditor, ExamRenderer: MatchingRenderer, ReviewRenderer: MatchingRenderer, responseSchema: z.string(), configSchema: z.object({}), createDefault: (number) => { const options = newOptions(); return { question_type: "matching", instruction: "Match each prompt with the correct option.", config: { options }, order_index: 0, questions: [{ id: crypto.randomUUID(), number, prompt: "Item to match", config: {}, answer_key: { kind: "SINGLE_OPTION", value: options[0].id }, order_index: 0 }] }; } },
];

for (const [id, label] of [["plan_labelling", "Plan Labelling"], ["map_labelling", "Map Labelling"], ["diagram_labelling", "Diagram Labelling"]] as const) {
  definitions.push({ id, label, category: "listening", BuilderEditor: VisualLabellingEditor, AnswerKeyEditor: VisualLabellingEditor, ExamRenderer: VisualLabellingRenderer, ReviewRenderer: VisualLabellingRenderer, responseSchema: z.string(), configSchema: z.object({}), createDefault: (number) => { const options = newOptions(); const questionId = crypto.randomUUID(); return { question_type: id, instruction: `Label the ${label.split(" ")[0].toLowerCase()}.`, config: { options, markers: [{ id: crypto.randomUUID(), question_id: questionId, x: 0.5, y: 0.5 }] }, order_index: 0, questions: [{ id: questionId, number, prompt: "Choose the correct label.", config: {}, answer_key: { kind: "SINGLE_OPTION", value: options[0].id }, order_index: 0 }] }; } });
}

for (const [id, label, kind] of [["form_completion", "Form Completion", "FORM"], ["note_completion", "Note Completion", "NOTE"], ["table_completion", "Table Completion", "TABLE"], ["flow_chart_completion", "Flow-chart Completion", "FLOW_CHART"], ["summary_completion", "Summary Completion", "SUMMARY"], ["sentence_completion", "Sentence Completion", "SENTENCE"]] as const) {
  definitions.push({ id, label, category: "listening", BuilderEditor: StructuredCompletionEditor, AnswerKeyEditor: StructuredCompletionEditor, ExamRenderer: StructuredCompletionRenderer, ReviewRenderer: StructuredCompletionRenderer, responseSchema: z.string(), configSchema: z.object({}), createDefault: (number) => { const question = textQuestion(number); const gap = { id: crypto.randomUUID(), type: "GAP" as const, text: "", question_id: question.id }; const layout = kind === "TABLE" ? { kind, columns: [{ id: crypto.randomUUID(), label: "Item" }, { id: crypto.randomUUID(), label: "Answer" }], rows: [{ id: crypto.randomUUID(), cells: [{ id: crypto.randomUUID(), type: "TEXT" as const, text: "Label" }, gap] }], nodes: [] } : { kind, columns: [], rows: [], nodes: [{ id: crypto.randomUUID(), type: "TEXT" as const, text: "Context", level: 0 }, { ...gap, level: 0 }] }; return { question_type: id, instruction: `Complete the ${label.replace(" Completion", "").toLowerCase()}.`, config: { layout }, order_index: 0, questions: [question] }; } });
}

definitions.push({ id: "short_answer", label: "Short Answer", category: "listening", BuilderEditor: TextCompletionEditor, AnswerKeyEditor: TextCompletionEditor, ExamRenderer: TextCompletionRenderer, ReviewRenderer: TextCompletionRenderer, responseSchema: z.string(), configSchema: z.object({}), createDefault: (number) => ({ question_type: "short_answer", instruction: "Answer using the stated word or number limit.", config: {}, order_index: 0, questions: [textQuestion(number)] }) });

export const questionRegistry = Object.fromEntries(definitions.map((item) => [item.id, item])) as Record<QuestionType, QuestionTypeDefinition>;
export const questionTypeOptions = definitions.map(({ id, label }) => ({ id, label }));
export const readingQuestionTypeOptions = definitions.filter((item) => item.category !== "listening").map(({ id, label }) => ({ id, label }));
export const listeningQuestionTypeOptions = definitions.filter((item) => item.category !== "reading").map(({ id, label }) => ({ id, label }));
